//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProyectoTaller2.C_Datos
{
    using System;
    using System.Collections.Generic;
    
    public partial class usuarios
    {
        public int id_usuario { get; set; }
        public string nombre { get; set; }
        public string apellido { get; set; }
        public int dni { get; set; }
        public string telefono { get; set; }
        public string direccion { get; set; }
        public string usuario { get; set; }
        public string contrasena { get; set; }
        public int rol_id { get; set; }
        public Nullable<System.DateTime> fecha_alta { get; set; }
    
        public virtual rol_usuario rol_usuario { get; set; }
    }
}
